packages:
  - themes/*
  - packages/*
  - scripts

# engineStrict: true
# strictPeerDependencies: true
shellEmulator: true
preferWorkspacePackages: true
linkWorkspacePackages: true
enablePrePostScripts: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@deox/*"

catalog:
  "@tsdown/css": "^0.22.0"
  "@types/node": "^25.8.0"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"
  blogger-plugin: "^0.0.11"
  react: "^19.2.6"
  react-dom: "^19.2.6"
  tsdown: "^0.22.0"
  vite: "^8.0.13"

allowBuilds:
  "@firebase/util": true
  "@swc/core": true
  esbuild: true
  msw: true
  protobufjs: true
