name: Deploy

on:
  push:
    branches:
      - development

jobs:
  publish:
    name: Build and Deploy
    runs-on: [ubuntu-latest]
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: ["22.x"]
    steps:
      - name: "Checkout ${{ github.ref_name }} branch"
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - name: Use pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Update npm
        run: npm i -g npm@10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: "pnpm run build"
        env:
          VITE_BASE: "https://cdn.jsdelivr.net/gh/${{ github.repository }}@static-dev"

      - name: Ensure static branch exists
        run: |
          current_branch=$(git symbolic-ref --short HEAD)
          if git show-ref --verify --quiet refs/remotes/origin/static-dev; then
            echo "✅ Branch 'static-dev' exists"
          else
            echo "⚡ Creating 'static-dev' branch"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git checkout --orphan static-dev
            git reset --hard
            git commit --allow-empty -m "chore: initial commit for static-dev branch"
            git push origin static-dev
            git checkout "$current_branch"
          fi

      - name: Deploy to static-dev branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: static-dev
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploy static assets from development branch"

  purge:
    name: Purge JsDelivr
    needs: [publish]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout static-dev branch
        uses: actions/checkout@v5
        with:
          ref: static-dev
          fetch-depth: 2

      - name: Install curl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Send Purge Requests to jsDelivr for all assets
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
              changed_files=$(git diff --name-only HEAD^ HEAD)
          else
              changed_files=$(git ls-tree -r --name-only HEAD)
          fi

          if [ -z "$changed_files" ]; then
            echo "No files changed. Skipping purge."
            exit 0
          fi

          for file in $changed_files; do
            url="https://purge.jsdelivr.net/gh/${{ github.repository }}@static-dev/$file"
            echo "Purging $url"
            curl -sS "$url" &
          done

          wait
          echo -e "\nAll purge requests for changed files have been sent."
